# PostgreSQL
spring.datasource.url=jdbc:postgresql://magicvetov-postgres:5432/magicvetov_db
spring.datasource.username=magicvetov_user
spring.datasource.password=strong_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate - отключаем валидацию схемы (Flyway управляет миграциями)
spring.jpa.hibernate.ddl-auto=none

# Redis
spring.data.redis.host=magicvetov-redis
spring.data.redis.port=6379
spring.data.redis.timeout=2000

# S3 (MinIO)
s3.access-key=accesskey
s3.secret-key=secretkey
s3.endpoint=http://magicvetov-minio:9000
s3.bucket=magicvetov

# Остальные настройки наследуются из application.properties