-- V30: Обновление цен и скрытие товаров по данным из Excel

-- 1. Скрываем товары со статусом 'удалить'
UPDATE products SET is_available = false WHERE name = 'Монобукет из 5 коралловых георгинов в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 5 розовых георгинов в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 5 персиковые георгинов в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 5 георгин Эвелин в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 5 желтых георгинов в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 алых георгинов в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 георгин Эвелин в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 коралловых георгинов в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 бордовых георгинов в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 желтых георгинов в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 пионовидных Роз Campanella в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 9 белых Хризантем Viena';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 пионовидных Роз Campanella в упаковке с тишью';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 пионовидных Роз Campanella под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 7 пионовидных Роз Campanella под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 9 георгинов';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 нежных георгинов';
UPDATE products SET is_available = false WHERE name = 'Монобукет из георгинов Пастельные мечты';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 9 терракотовых кустовых Хризантем';
UPDATE products SET is_available = false WHERE name = 'Монобукет 51 Роза микс №7 в крафте';
UPDATE products SET is_available = false WHERE name = 'Монобукет синие Гиацинты 25 шт под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет синие Гиацинты 25 шт';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 Роз Royal Park под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 Роз Royal Park под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 11 пионовидных Роз Campanella под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет из Лаванды увеличенный в крафте';
UPDATE products SET is_available = false WHERE name = 'Монобукет из Лаванды в крафте';
UPDATE products SET is_available = false WHERE name = 'Монобукет из Лаванды в крафте №1';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 21 ст. Вербы в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 15 ст. Вербы';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 15 синих Гиацинтов';
UPDATE products SET is_available = false WHERE name = 'Монобукет из Лаванды в крафте №2';
UPDATE products SET is_available = false WHERE name = 'Монобукет 101 розовый тюльпан под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 49 белых Фрезий';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 19 белых Ирисов';
UPDATE products SET is_available = false WHERE name = 'Монобукет 51 тюльпан “Каламбус” под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 51 белый тюльпан под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет из розовой гортензии с эвкалиптом';
UPDATE products SET is_available = false WHERE name = 'Монобукет из голубой гортензии с эвкалиптом';
UPDATE products SET is_available = false WHERE name = 'Монобукет из белых лилий с эвкалиптом';
UPDATE products SET is_available = false WHERE name = 'Монобукет из розовых лилий с эвкалиптом';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 роз микс дуо 2';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 роз микс дуо 1';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 роз микс 6';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 роз микс 5';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 роз микс 2';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 роз микс 1';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 роз Lemonade Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 роз Lemonade Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 11 роз Explorer Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет 7 роз Luciano Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 роз Luciano Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 3 роз Favourite Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 3 роз Country Blues Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 9 красных Хризантем';
UPDATE products SET is_available = false WHERE name = 'Монобукет 17 Роз Hermosa Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет 17 Роз Explorer Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет Сияние лета';
UPDATE products SET is_available = false WHERE name = 'Монобукет 17 Роз Absolut In Pink под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 17 пионовидных Роз Candy X-pression под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 Роз Wasabi в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 пионовидных Роз Playa blanca в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 пионовидных Роз Kahala в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 пионовидных Роз Country blues в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 пионовидных Роз Candlelight в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 11 кустовых роз Apricot Lace в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 11 Роз Vendela в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 11 Роз Lemonade в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 11 Роз Crème de la crème в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 11 Роз Chekmate в упаковке';
UPDATE products SET is_available = false WHERE name = 'Букет Симфония Red';
UPDATE products SET is_available = false WHERE name = 'Монобукет 51 розовый тюльпан';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 15 тюльпанов микс в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 15 тюльпанов Каламбус в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 9 тюльпанов в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 25 Роз Favourite под ленту';
UPDATE products SET is_available = false WHERE name = 'Букет из 5 пионов Madame Clote Thain и роз в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 розовых пионов №2';
UPDATE products SET is_available = false WHERE name = 'Монобукет Пион 35 шт';
UPDATE products SET is_available = false WHERE name = 'Монобукет Пион 11 шт';
UPDATE products SET is_available = false WHERE name = 'Монобукет 3 кустовых роз Royal Porcelaine в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 3 кустовых роз Aerobic в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 3 кустовых роз Misty Bubbles в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 кустовых роз Scarlett в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 кустовых роз Royal Porcelaine в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 кустовых роз Misty Bubbles в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 кустовых роз Aerobic в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 кустовых роз Apricot Lace  в белой упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 кустовых роз Apricot Lace  в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 25 кустовых роз Porcelaine в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 21 герберы под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 51 Розы Кения под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 кустовых роз Misty Bubbles  в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 кустовых роз Aerobic в упаковке с тишью';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 кустовых роз Misty Bubbles под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет Ромашки 19 шт';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 Пионов Duchesse в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 Пионов Jacorma в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 Пионов Etched Salmon в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 Пионов Duchesse под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 Пионов Old faithful под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 Пионов Coral Sunset';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 Пионов Jacorma';
UPDATE products SET is_available = false WHERE name = 'Монобукет Ромашки 51 шт №2';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 Пионов Etched Salmon';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 Пионов Duchesse';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 Пионов Old faithful';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 Пионов Coral Sunset';
UPDATE products SET is_available = false WHERE name = 'Монобукет 19 Пионов Jacorma';
UPDATE products SET is_available = false WHERE name = 'Монобукет 11 Пионов Duchesse';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 5 Гортензий';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 Роз Tanya под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 Роз Porcelaine под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 Роз Pink Dimension под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 7 Роз Pink Dimension под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 7 Роз Tanya под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 7 Роз Royal Park под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 7 Роз Porcelaine под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 Роз Porcelaine под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 Роз Pink Dimension под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 роз Favourite Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 роз Favourite Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет 15 роз Luciano Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет 17 Роз Pink O''Hara Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет 17 Роз White O''Hara Французский поцелуй';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 георгинов микс в упаковке';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 пионов Belgravia';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 пионов Red charm';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 7 пионов Madame Clote Thain';
UPDATE products SET is_available = false WHERE name = 'Монобукет из 25 желтых нарциссов';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 кустовых роз Sophy под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 7 кустовых роз Sophy под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 7 кустовых роз Femke под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 5 кустовых роз Femke под ленту';
UPDATE products SET is_available = false WHERE name = 'Монобукет 11 Пионов Old faithful';
UPDATE products SET is_available = false WHERE name = 'Монобукет 11 Пионов Coral Sunset';
UPDATE products SET is_available = false WHERE name = 'Монобукет 11 Пионов Jacorma';
UPDATE products SET is_available = false WHERE name = 'Монобукет 7 белых пионов';
UPDATE products SET is_available = false WHERE name = 'Монобукет Пион 25 шт';
UPDATE products SET is_available = false WHERE name = 'Монобукет Пион 19 шт';
UPDATE products SET is_available = false WHERE name = 'Монобукет 9 белых пионов';

-- 2. Обновляем цены для товаров 'в наличии'
UPDATE products SET price = 2390.00, is_available = true WHERE name = 'Монобукет из 7 лавандовых Гипсофил';
UPDATE products SET price = 3190.00, is_available = true WHERE name = 'Монобукет 9 Роз Explorer в упаковке с тишью 2';
UPDATE products SET price = 3190.00, is_available = true WHERE name = 'Монобукет 9 Роз Mondial в упаковке с тишью';
UPDATE products SET price = 5990.00, is_available = true WHERE name = 'Монобукет 9 кустовых роз в упаковке с тишью';
UPDATE products SET price = 2390.00, is_available = true WHERE name = 'Монобукет из 7 цветных гипсофил';
UPDATE products SET price = 2390.00, is_available = true WHERE name = 'Монобукет из 7 белых Гипсофил';
UPDATE products SET price = 2990.00, is_available = true WHERE name = 'Монобукет из 11 гербер в упаковке';
UPDATE products SET price = 1690.00, is_available = true WHERE name = 'Монобукет 5 Роз Explorer в упаковке';
UPDATE products SET price = 1690.00, is_available = true WHERE name = 'Монобукет 5 Роз Pink Floyd в упаковке';
UPDATE products SET price = 1690.00, is_available = true WHERE name = 'Монобукет 5 Роз Mondial в упаковке';
UPDATE products SET price = 2190.00, is_available = true WHERE name = 'Монобукет из 5 Роз Mondial в упаковке';
UPDATE products SET price = 2190.00, is_available = true WHERE name = 'Монобукет из 5 Роз Explorer в упаковке';
UPDATE products SET price = 3190.00, is_available = true WHERE name = 'Монобукет из 11 гербер в упаковке';
UPDATE products SET price = 2490.00, is_available = true WHERE name = 'Монобукет из 7 гербер в упаковке';
UPDATE products SET price = 3490.00, is_available = true WHERE name = 'Монобукет 9 Роз Explorer в упаковке с тишью';
UPDATE products SET price = 3490.00, is_available = true WHERE name = 'Монобукет 9 Роз Pink Floyd в упаковке с тишью';
UPDATE products SET price = 3490.00, is_available = true WHERE name = 'Монобукет 9 Роз Mondial в светло-зеленой упаковке с тишью';
UPDATE products SET price = 4790.00, is_available = true WHERE name = 'Монобукет 9 кустовых роз Femke №2  в упаковке';
UPDATE products SET price = 4790.00, is_available = true WHERE name = 'Монобукет 9 кустовых роз  в упаковке';
UPDATE products SET price = 2990.00, is_available = true WHERE name = 'Монобукет 9 Роз Explorer под ленту';
UPDATE products SET price = 3390.00, is_available = true WHERE name = 'Монобукет 9 Роз Mondial под ленту';
UPDATE products SET price = 2190.00, is_available = true WHERE name = 'Монобукет 7 Роз Explorer под ленту';
UPDATE products SET price = 2190.00, is_available = true WHERE name = 'Монобукет 7 Роз Pink Floyd под ленту';
UPDATE products SET price = 2190.00, is_available = true WHERE name = 'Монобукет 7 Роз Mondial под ленту';
UPDATE products SET price = 10890.00, is_available = true WHERE name = 'Монобукет из 31 кустовой Хризантемы микс';
UPDATE products SET price = 5390.00, is_available = true WHERE name = 'Монобукет из 15 кустовых Хризантем микс';
UPDATE products SET price = 3990.00, is_available = true WHERE name = 'Монобукет из 11 кустовых Хризантем микс';
UPDATE products SET price = 3290.00, is_available = true WHERE name = 'Монобукет из 9 кустовых Хризантем микс';
UPDATE products SET price = 5390.00, is_available = true WHERE name = 'Монобукет из 15 желтых Хризантем №2';
UPDATE products SET price = 5390.00, is_available = true WHERE name = 'Монобукет из 15 белых Хризантем №2';
UPDATE products SET price = 3290.00, is_available = true WHERE name = 'Монобукет из 9 розовых кустовых Хризантем';
UPDATE products SET price = 3290.00, is_available = true WHERE name = 'Монобукет из 9 белых кустовых Хризантем';
UPDATE products SET price = 3290.00, is_available = true WHERE name = 'Монобукет из 9 желтых кустовых Хризантем';
UPDATE products SET price = 9990.00, is_available = true WHERE name = 'Монобукет 51 Роза микс-5 под ленту';
UPDATE products SET price = 6990.00, is_available = true WHERE name = 'Монобукет 51 Роза микс-4 под ленту';
UPDATE products SET price = 2690.00, is_available = true WHERE name = 'Монобукет из 7 кустовых Хризантем микс';
UPDATE products SET price = 2690.00, is_available = true WHERE name = 'Монобукет из 7 кустовых терракотовых Хризантем';
UPDATE products SET price = 2690.00, is_available = true WHERE name = 'Монобукет из 7 кустовых лавандовых Хризантем';
UPDATE products SET price = 2690.00, is_available = true WHERE name = 'Монобукет из 7 кустовых белых Хризантем';
UPDATE products SET price = 1990.00, is_available = true WHERE name = 'Монобукет из 5 кустовых терракотовых Хризантем';
UPDATE products SET price = 1990.00, is_available = true WHERE name = 'Монобукет из 5 кустовых желтых Хризантем под ленту';
UPDATE products SET price = 1990.00, is_available = true WHERE name = 'Монобукет из 5 кустовых белых Хризантем под ленту';
UPDATE products SET price = 1990.00, is_available = true WHERE name = 'Монобукет из 5 кустовых лавандовых Хризантем';
UPDATE products SET price = 7790.00, is_available = true WHERE name = 'Монобукет из 25 стеблей Танацетума';
UPDATE products SET price = 3490.00, is_available = true WHERE name = 'Монобукет Гвоздика 21шт Микс';
UPDATE products SET price = 3490.00, is_available = true WHERE name = 'Монобукет Гвоздика Брют 21шт';
UPDATE products SET price = 2990.00, is_available = true WHERE name = 'Монобукет Маттиола лавандовая 9 шт';
UPDATE products SET price = 2590.00, is_available = true WHERE name = 'Монобукет из 3 Гортензий Микс';
UPDATE products SET price = 3990.00, is_available = true WHERE name = 'Монобукет из 9 желтых Хризантем Magnum';
UPDATE products SET price = 3990.00, is_available = true WHERE name = 'Монобукет из 9 белых Хризантем Magnum';
UPDATE products SET price = 7490.00, is_available = true WHERE name = 'Монобукет из 11 Гортензий';
UPDATE products SET price = 3790.00, is_available = true WHERE name = 'Монобукет из 3 белых Гортензий';
UPDATE products SET price = 5990.00, is_available = true WHERE name = 'Монобукет из 15 белых Роз в крафте';
UPDATE products SET price = 4290.00, is_available = true WHERE name = 'Монобукет 5 Лилий';
UPDATE products SET price = 2890.00, is_available = true WHERE name = 'Букет из 9 цветных гипсофил';
UPDATE products SET price = 2890.00, is_available = true WHERE name = 'Монобукет из 9 белых Гипсофил';
UPDATE products SET price = 5890.00, is_available = true WHERE name = 'Монобукет из 15 малиновых Роз микс 3 в упаковке с тишью';
UPDATE products SET price = 3990.00, is_available = true WHERE name = 'Монобукет бело-розовый микс из 11 эквадорских Роз в упаковке с тишью';
UPDATE products SET price = 3990.00, is_available = true WHERE name = 'Монобукет 11 Роз микс в упаковке с тишью';
UPDATE products SET price = 3990.00, is_available = true WHERE name = 'Монобукет 11 Роз Tibet в упаковке с тишью';
UPDATE products SET price = 3590.00, is_available = true WHERE name = 'Букет из 11 роз Pink Floyd';
UPDATE products SET price = 4190.00, is_available = true WHERE name = 'Монобукет 11 Роз Pink Floyd в упаковке с тишью';
UPDATE products SET price = 4190.00, is_available = true WHERE name = 'Монобукет из 11 Роз Mondial в упаковке с тишью';
UPDATE products SET price = 3590.00, is_available = true WHERE name = 'Монобукет 11 Роз Explorer под ленту';
UPDATE products SET price = 3890.00, is_available = true WHERE name = 'Монобукет 11 Роз Explorer в пленке';
UPDATE products SET price = 3590.00, is_available = true WHERE name = 'Монобукет 11 Роз Mondial под ленту';
UPDATE products SET price = 3890.00, is_available = true WHERE name = 'Монобукет 11 Роз Mondial в крафте';
UPDATE products SET price = 3590.00, is_available = true WHERE name = 'Монобукет из 15 белых роз Россия в упаковке';
UPDATE products SET price = 3290.00, is_available = true WHERE name = 'Монобукет из 15 белых роз Россия под ленту';
UPDATE products SET price = 3590.00, is_available = true WHERE name = 'Монобукет бело-розовый микс из 15 роз Россия в упаковке 2';
UPDATE products SET price = 3290.00, is_available = true WHERE name = 'Монобукет бело-розовый микс из 15 роз Россия под ленту 2';
UPDATE products SET price = 3590.00, is_available = true WHERE name = 'Монобукет из 15 роз микс Россия в упаковке';
UPDATE products SET price = 3590.00, is_available = true WHERE name = 'Монобукет бело-розовый микс из 15 роз Россия в упаковке 1';
UPDATE products SET price = 3290.00, is_available = true WHERE name = 'Монобукет из 15 роз микс Россия под ленту';
UPDATE products SET price = 3290.00, is_available = true WHERE name = 'Монобукет бело-розовый микс из 15 роз Россия под ленту 1';
UPDATE products SET price = 2990.00, is_available = true WHERE name = 'Монобукет из 9 гербер с эвкалиптом';
UPDATE products SET price = 1590.00, is_available = true WHERE name = 'Монобукет из 5 роз Explorer под ленту';
UPDATE products SET price = 1590.00, is_available = true WHERE name = 'Монобукет из 5 роз Pink Floyd под ленту';
UPDATE products SET price = 1590.00, is_available = true WHERE name = 'Монобукет из 5 роз Mondial под ленту';
UPDATE products SET price = 1190.00, is_available = true WHERE name = 'Монобукет из 5 альстромерий микс под ленту';
UPDATE products SET price = 1490.00, is_available = true WHERE name = 'Монобукет из 5 гербер моно в упаковке';
UPDATE products SET price = 1190.00, is_available = true WHERE name = 'Монобукет из 5 гербер микс';
UPDATE products SET price = 1490.00, is_available = true WHERE name = 'Монобукет из 5 гербер микс в упаковке';
UPDATE products SET price = 1090.00, is_available = true WHERE name = 'Монобукет из 3 белых кустовых хризантем под ленту';
UPDATE products SET price = 1190.00, is_available = true WHERE name = 'Монобукет из 5 белых гербер под ленту';
UPDATE products SET price = 1190.00, is_available = true WHERE name = 'Монобукет из 5 альстромерий под ленту';
UPDATE products SET price = 1190.00, is_available = true WHERE name = 'Монобукет из 5 альстромерий микс под ленту';
UPDATE products SET price = 2690.00, is_available = true WHERE name = 'Монобукет из 7 роз микс 3';
UPDATE products SET price = 2990.00, is_available = true WHERE name = 'Монобукет из 7 роз Explorer Французский поцелуй';
UPDATE products SET price = 2590.00, is_available = true WHERE name = 'Монобукет из 5 роз Explorer Французский поцелуй';
UPDATE products SET price = 6890.00, is_available = true WHERE name = 'Монобукет из 15 роз Explorer Французский поцелуй';
UPDATE products SET price = 3590.00, is_available = true WHERE name = 'Монобукет из 7 роз Mondial Французский поцелуй';
UPDATE products SET price = 1290.00, is_available = true WHERE name = 'Монобукет из 3 роз Mondial Французский поцелуй';
UPDATE products SET price = 7590.00, is_available = true WHERE name = 'Монобукет 15 кустовых роз в упаковке с тишью';
UPDATE products SET price = 6490.00, is_available = true WHERE name = 'Монобукет из 7 пионов Sarah Bernhardt';
UPDATE products SET price = 7890.00, is_available = true WHERE name = 'Монобукет 25 Роз Pink Mondial под ленту';
UPDATE products SET price = 3690.00, is_available = true WHERE name = 'Монобукет 11 Роз Pink Mondial под ленту';
UPDATE products SET price = 3690.00, is_available = true WHERE name = 'Монобукет 11 Роз Lola под ленту';
